import React from "react";
import type { Metadata } from "next";
import "./style/barebone.css";
import Script from "next/script"; // next/script import 추가

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body>{children}</body>
      {/* ChannelIO 스크립트 삽입 */}
      <Script
        id="channel-io"
        strategy="lazyOnload" // 페이지 로드 이후 비동기로 실행
      >
        {`
            (function(){var w=window;if(w.ChannelIO){return w.console.error("ChannelIO script included twice.");}var ch=function(){ch.c(arguments);};ch.q=[];ch.c=function(args){ch.q.push(args);};w.ChannelIO=ch;function l(){if(w.ChannelIOInitialized){return;}w.ChannelIOInitialized=true;var s=document.createElement("script");s.type="text/javascript";s.async=true;s.src="https://cdn.channel.io/plugin/ch-plugin-web.js";var x=document.getElementsByTagName("script")[0];if(x.parentNode){x.parentNode.insertBefore(s,x);}}if(document.readyState==="complete"){l();}else{w.addEventListener("DOMContentLoaded",l);w.addEventListener("load",l);}})();
            ChannelIO('boot', {
              "pluginKey": "e195316a-d095-49e4-aa76-438785cc30e1",
              "hideChannelButtonOnBoot": true
            });
          `}
      </Script>
    </html>
  );
}

export default RootLayout;
